//REMOVE
const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST';
const REMOVE_USER_REQUEST_FAILURE = 'REMOVE_USER_REQUEST_FAILURE';
const REMOVE_USER_REQUEST_SUCCESS = 'REMOVE_USER_REQUEST_SUCCESS';
//UPDATE
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_REQUEST_FAILURE = 'UPDATE_USER_REQUEST_FAILURE';
const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';

export {
  REMOVE_USER_REQUEST,
  REMOVE_USER_REQUEST_FAILURE,
  REMOVE_USER_REQUEST_SUCCESS,
  UPDATE_USER_REQUEST,
  UPDATE_USER_REQUEST_FAILURE,
  UPDATE_USER_REQUEST_SUCCESS,
};
