//LOGIN
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
//SIGNUP
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';
const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';

//LOGOUT
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';

//LOGOUT
const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
const GET_TOKEN_REQUEST_FAILURE = 'GET_TOKEN_REQUEST_FAILURE';
const GET_TOKEN_REQUEST_SUCCESS = 'GET_TOKEN_REQUEST_SUCCESS';

export {
  LOGIN_REQUEST,
  LOGIN_REQUEST_FAILURE,
  LOGIN_REQUEST_SUCCESS,
  SIGNUP_REQUEST,
  SIGNUP_REQUEST_FAILURE,
  SIGNUP_REQUEST_SUCCESS,
  LOGOUT_REQUEST,
  LOGOUT_REQUEST_FAILURE,
  LOGOUT_REQUEST_SUCCESS,
  GET_TOKEN_REQUEST,
  GET_TOKEN_REQUEST_FAILURE,
  GET_TOKEN_REQUEST_SUCCESS,
};
