//ADD
const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
const ADD_EMPLOYEE_REQUEST_FAILURE = 'ADD_EMPLOYEE_REQUEST_FAILURE';
const ADD_EMPLOYEE_REQUEST_SUCCESS = 'ADD_EMPLOYEE_REQUEST_SUCCESS';
//GET ONE
const GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST';
const GET_EMPLOYEE_REQUEST_FAILURE = 'GET_EMPLOYEE_REQUEST_FAILURE';
const GET_EMPLOYEE_REQUEST_SUCCESS = 'GET_EMPLOYEE_REQUEST_SUCCESS';
//GET ALL
const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
const GET_EMPLOYEES_REQUEST_FAILURE = 'GET_EMPLOYEES_REQUEST_FAILURE';
const GET_EMPLOYEES_REQUEST_SUCCESS = 'GET_EMPLOYEES_REQUEST_SUCCESS';
//REMOVE
const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST';
const REMOVE_EMPLOYEE_REQUEST_FAILURE = 'REMOVE_EMPLOYEE_REQUEST_FAILURE';
const REMOVE_EMPLOYEE_REQUEST_SUCCESS = 'REMOVE_EMPLOYEE_REQUEST_SUCCESS';
//UPDATE
const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
const UPDATE_EMPLOYEE_REQUEST_FAILURE = 'UPDATE_EMPLOYEE_REQUEST_FAILURE';
const UPDATE_EMPLOYEE_REQUEST_SUCCESS = 'UPDATE_EMPLOYEE_REQUEST_SUCCESS';

export {
  ADD_EMPLOYEE_REQUEST,
  ADD_EMPLOYEE_REQUEST_FAILURE,
  ADD_EMPLOYEE_REQUEST_SUCCESS,
  GET_EMPLOYEE_REQUEST,
  GET_EMPLOYEE_REQUEST_FAILURE,
  GET_EMPLOYEE_REQUEST_SUCCESS,
  GET_EMPLOYEES_REQUEST,
  GET_EMPLOYEES_REQUEST_FAILURE,
  GET_EMPLOYEES_REQUEST_SUCCESS,
  REMOVE_EMPLOYEE_REQUEST,
  REMOVE_EMPLOYEE_REQUEST_FAILURE,
  REMOVE_EMPLOYEE_REQUEST_SUCCESS,
  UPDATE_EMPLOYEE_REQUEST,
  UPDATE_EMPLOYEE_REQUEST_FAILURE,
  UPDATE_EMPLOYEE_REQUEST_SUCCESS,
};
